import json
from sqlalchemy.orm import Session
from ..database import crud
from ..ai.attack_explainer import explain_attack
from ..ai.report_generator import generate_daily_report
from ..ai.recommendation_engine import get_recommendations
from ..ai.chat_assistant import chat_with_assistant
from ..utils.security_score import compute_security_score
from ..utils.logger import ai_logger


async def explain_attack_log(db: Session, log_id: int) -> dict:
    log = crud.get_attack_log_by_id(db, log_id)
    if not log:
        return {"error": "Attack log not found"}
    attack_data = {
        "payload": log.payload, "attack_type": log.attack_type,
        "threat_score": log.threat_score, "severity": log.severity,
        "endpoint": log.endpoint, "ip_address": log.ip_address, "method": log.method,
    }
    explanation = await explain_attack(attack_data)
    ai_logger.info(f"AI explained attack #{log_id}")
    try:
        return json.loads(explanation)
    except json.JSONDecodeError:
        return {"explanation": explanation}


async def generate_report(db: Session, generated_by: str = "admin") -> dict:
    attacks = crud.count_attacks_today(db)
    logins = crud.count_logins_today(db)
    top_eps = crud.get_top_attacked_endpoints(db, limit=1)
    top_types = crud.get_attack_type_distribution(db)
    top_ips = crud.get_top_attacker_ips(db, limit=1)

    stats = {
        "total_requests": attacks["total"],
        "blocked_requests": attacks["blocked"],
        "allowed_requests": attacks["allowed"],
        "successful_logins": logins["successful"],
        "failed_logins": logins["failed"],
        "top_endpoint": top_eps[0]["endpoint"] if top_eps else "N/A",
        "top_attack_type": top_types[0]["type"] if top_types else "N/A",
        "top_attacker_ip": top_ips[0]["ip"] if top_ips else "N/A",
        "security_score": compute_security_score(db),
        "total_users": crud.count_users(db),
        "vault_records": crud.count_vault_items(db),
    }

    content = await generate_daily_report(stats)
    report = crud.create_ai_report(db, "daily", content, generated_by)
    ai_logger.info(f"AI report generated by {generated_by}")
    return {"id": report.id, "content": content, "generated_at": str(report.generated_at)}


async def get_ai_recommendations(db: Session) -> list:
    attacks = crud.count_attacks_today(db)
    logins = crud.count_logins_today(db)
    top_eps = crud.get_top_attacked_endpoints(db, limit=1)
    top_types = crud.get_attack_type_distribution(db)

    stats = {
        "failed_logins": logins["failed"],
        "blocked_requests": attacks["blocked"],
        "top_attack_type": top_types[0]["type"] if top_types else "N/A",
        "top_endpoint": top_eps[0]["endpoint"] if top_eps else "N/A",
        "security_score": compute_security_score(db),
    }

    result = await get_recommendations(stats)
    try:
        return json.loads(result)
    except json.JSONDecodeError:
        return [{"title": "AI Response", "description": result, "priority": "medium", "category": "general"}]


async def chat(db: Session, user_id: int, message: str) -> str:
    # Build context from recent data
    recent_attacks = crud.get_attack_logs(db, limit=10)
    logins = crud.count_logins_today(db)
    attacks = crud.count_attacks_today(db)

    context_parts = [
        f"Today's stats: {attacks['total']} requests, {attacks['blocked']} blocked, "
        f"{logins['successful']} successful logins, {logins['failed']} failed logins.",
    ]
    for a in recent_attacks[:5]:
        context_parts.append(
            f"Attack #{a.id}: {a.attack_type} from {a.ip_address} on {a.endpoint} "
            f"(score: {a.threat_score}, action: {a.action})"
        )

    context = "\n".join(context_parts)

    # Load and format conversation history (up to last 10 messages)
    history_msgs = crud.get_chat_history(db, user_id, limit=10)
    history_parts = []
    for msg in reversed(history_msgs):
        role_label = "User" if msg.role == "user" else "Assistant"
        history_parts.append(f"{role_label}: {msg.content}")
    chat_history_str = "\n".join(history_parts)

    # Save user message
    crud.save_chat_message(db, user_id, "user", message)

    # Get AI response with conversation context
    reply = await chat_with_assistant(message, context, chat_history_str)

    # Save AI reply
    crud.save_chat_message(db, user_id, "assistant", reply)

    return reply
